<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\**" />
    <Compile Remove="Internal\**" />
    <Compile Remove="Public\**" />
    <EmbeddedResource Remove="Dtos\**" />
    <EmbeddedResource Remove="Internal\**" />
    <EmbeddedResource Remove="Public\**" />
    <None Remove="Dtos\**" />
    <None Remove="Internal\**" />
    <None Remove="Public\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Explorer.BuildingBlocks.Core\Explorer.BuildingBlocks.Core.csproj" />
  </ItemGroup>

</Project>
